### ISSUE TITLE
1.1.1 fails to build on node v0.10.33

### ISSUE THREAD

**Issue by sebmck** [jprichardson/node-kexec#16]
```
> kexec@1.1.1 install /Users/sebastian/Projects/6to5/6to5/node_modules/kexec
> pangyp configure build

  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc:39:25: error: unknown type name 'FunctionCallbackInfo'
static void kexec(const FunctionCallbackInfo<Value>& args) {
                        ^
../src/kexec.cc:39:45: error: expected ')'
static void kexec(const FunctionCallbackInfo<Value>& args) {
                                            ^
../src/kexec.cc:39:18: note: to match this '('
static void kexec(const FunctionCallbackInfo<Value>& args) {
                 ^
../src/kexec.cc:41:17: error: no matching constructor for initialization of 'v8::HandleScope'
    HandleScope scope(isolate);
                ^     ~~~~~~~
/Users/sebastian/.node-gyp/0.10.33/deps/v8/include/v8.h:473:3: note: candidate constructor not viable: no known conversion from 'v8::Isolate *' to 'const v8::HandleScope' for 1st
      argument
  HandleScope(const HandleScope&);
  ^
/Users/sebastian/.node-gyp/0.10.33/deps/v8/include/v8.h:448:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../src/kexec.cc:67:15: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if ( 1 == args.Length() && args[0]->IsString() )
              ^~~~
              uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:67:15: error: invalid use of non-static data member 'args'
    if ( 1 == args.Length() && args[0]->IsString() )
              ^~~~
../src/kexec.cc:67:32: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if ( 1 == args.Length() && args[0]->IsString() )
                               ^~~~
                               uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:67:32: error: invalid use of non-static data member 'args'
    if ( 1 == args.Length() && args[0]->IsString() )
                               ^~~~
../src/kexec.cc:69:33: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
        String::Utf8Value v8str(args[0]);
                                ^~~~
                                uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:69:33: error: invalid use of non-static data member 'args'
        String::Utf8Value v8str(args[0]);
                                ^~~~
../src/kexec.cc:75:50: error: too many arguments to function call, expected single argument 'value', have 2 arguments
        Local<Number> num = Number::New(isolate, err);
                            ~~~~~~~~~~~          ^~~
/Users/sebastian/.node-gyp/0.10.33/deps/v8/include/v8.h:1381:12: note: 'New' declared here
  V8EXPORT static Local<Number> New(double value);
           ^
../src/kexec.cc:76:9: error: use of undeclared identifier 'args'; did you mean 'argv'?
        args.GetReturnValue().Set(num);
        ^~~~
        argv
../src/kexec.cc:70:15: note: 'argv' declared here
        char* argv[] = { const_cast<char *>("/bin/sh"), const_cast<char *>("-c"), *v8str, NULL};
              ^
../src/kexec.cc:76:13: error: member reference base type 'char *[4]' is not a structure or union
        args.GetReturnValue().Set(num);
        ~~~~^~~~~~~~~~~~~~~
../src/kexec.cc:83:15: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
              ^~~~
              uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:83:15: error: invalid use of non-static data member 'args'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
              ^~~~
../src/kexec.cc:83:32: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                               ^~~~
                               uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:83:32: error: invalid use of non-static data member 'args'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                               ^~~~
../src/kexec.cc:83:55: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                                                      ^~~~
                                                      uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../src/kexec.cc:83:55: error: invalid use of non-static data member 'args'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                                                      ^~~~
../src/kexec.cc:85:33: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
        String::Utf8Value v8str(args[0]);
                                ^~~~
                                uv_process_options_s::args
/Users/sebastian/.node-gyp/0.10.33/deps/uv/include/uv.h:1326:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
```

Reference: 6to5/6to5#691

**Comment by jprichardson** [comment]
I'm unable to reproduce this. I'm using OS X Yosemite, which OS X version are you using?

**Comment by sebmck** [comment]
Yep, Yosemite, 10.10.1.
