### ISSUE TITLE
Fails to build on stable node release 0.12.0

### ISSUE THREAD

**Issue by mirek** [jprichardson/node-kexec#17]
mirekimac:kexec-test mirek$ sw_vers -productVersion 
    10.10.2
    mirekimac:kexec-test mirek$ node --version
    v0.12.0
    mirekimac:kexec-test mirek$ npm --version
    2.5.0
    mirekimac:kexec-test mirek$ npm install kexec
      CXX(target) Release/obj.target/kexec/src/kexec.o
    ../src/kexec.cc:22:30: error: use of undeclared identifier 'F_GETFD'
        int flags = fcntl (desc, F_GETFD, 0);
                                 ^
    ../src/kexec.cc:26:15: error: use of undeclared identifier 'FD_CLOEXEC'
        flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
                  ^
    ../src/kexec.cc:27:25: error: use of undeclared identifier 'F_SETFD'
        return fcntl (desc, F_SETFD, flags);
                            ^
    ../src/kexec.cc:43:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> kexec(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
          ^
    ../src/kexec.cc:44:17: error: calling a protected constructor of class 'v8::HandleScope'
        HandleScope scope;
                    ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
      V8_INLINE HandleScope() {}
                ^
    ../src/kexec.cc:67:19: error: member access into incomplete type 'const v8::internal::Arguments'
        if ( 1 == args.Length() && args[0]->IsString() )
                      ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
    class Arguments;
          ^
    ../src/kexec.cc:69:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
            String::Utf8Value v8str(args[0]);
                                    ~~~~^~
    ../src/kexec.cc:78:44: error: too few arguments to function call, expected 2, have 1
            Local<Number> num = Number::New(err);
                                ~~~~~~~~~~~    ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:3: note: 'New' declared here
      static Local<Number> New(Isolate* isolate, double value);
      ^
    ../src/kexec.cc:79:22: error: no member named 'Close' in 'v8::HandleScope'
            return scope.Close(num/*Undefined()*/);
                   ~~~~~ ^
    ../src/kexec.cc:83:19: error: member access into incomplete type 'const v8::internal::Arguments'
        if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                      ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
    class Arguments;
          ^
    ../src/kexec.cc:85:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
            String::Utf8Value v8str(args[0]);
                                    ~~~~^~
    ../src/kexec.cc:89:59: error: type 'const v8::internal::Arguments' does not provide a subscript operator
            Local<Array> argv_handle = Local<Array>::Cast(args[1]);
                                                          ~~~~^~
    ../src/kexec.cc:101:66: error: too few arguments to function call, expected 2, have 1
                String::Utf8Value arg(argv_handle->Get(Integer::New(i))->ToString());
                                                       ~~~~~~~~~~~~  ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 'New' declared here
      static Local<Integer> New(Isolate* isolate, int32_t value);
      ^
    ../src/kexec.cc:118:44: error: too few arguments to function call, expected 2, have 1
            Local<Number> num = Number::New(err);
                                ~~~~~~~~~~~    ^
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:3: note: 'New' declared here
      static Local<Number> New(Isolate* isolate, double value);
      ^
    ../src/kexec.cc:119:22: error: no member named 'Close' in 'v8::HandleScope'
            return scope.Close(num/*Undefined()*/);
                   ~~~~~ ^
    ../src/kexec.cc:127:49: error: no member named 'New' in 'v8::String'
        ThrowException(Exception::TypeError(String::New("kexec: invalid arguments")));
                                            ~~~~~~~~^
    ../src/kexec.cc:128:18: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(Undefined());
               ~~~~~ ^
    ../src/kexec.cc:128:24: error: no matching function for call to 'Undefined'
        return scope.Close(Undefined());
                           ^~~~~~~~~
    /Users/mirek/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
      friend Handle<Primitive> Undefined(Isolate* isolate);
                               ^
    ../src/kexec.cc:134:9: error: no matching function for call to 'NODE_SET_METHOD'
            NODE_SET_METHOD(target, "kexec", kexec);
            ^~~~~~~~~~~~~~~
    /Users/mirek/.node-gyp/0.12.0/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
    #define NODE_SET_METHOD node::NODE_SET_METHOD
                            ^~~~~~~~~~~~~~~~~~~~~
    /Users/mirek/.node-gyp/0.12.0/src/node.h:228:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable: no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback'
          (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
    inline void NODE_SET_METHOD(const TypeName& recv,
                ^
    19 errors generated.
    make: *** [Release/obj.target/kexec/src/kexec.o] Error 1

**Comment by jprichardson** [comment]
Should be fixed now: https://github.com/jprichardson/node-kexec/releases/tag/1.2.0
